#!/bin/sh -e

USERNAME="$1"

su - "${USERNAME}"
ssh-keygen -t ed25519 -o -a 100
chmod 600 ~/.ssh/id_ed25519*
cat ~/.ssh/id_ed25519.pub >> ~/.ssh/authorized_keys
usermod --append --groups ssh-user -- "${USERNAME}"
exit
