#!/bin/sh -e

readonly USERNAME="$1"

mkdir --mode 0600 --parents "/home/${USERNAME}/.ssh"
cd "/home/${USERNAME}/.ssh"
ssh-keygen -f id_ed25519 -t ed25519 -o -a 100 -C "${USERNAME}@$(hostname -f)"
cat id_ed25519.pub >> authorized_keys
chown --recursive "${USERNAME}":"${USERNAME}" ../.ssh
chmod 0700 ../.ssh
chmod 0600 ../.ssh/*
usermod --append --groups ssh-user -- "${USERNAME}"
